apiVersion: v1
kind: Secret
metadata:
  name: civicpulse-secrets
  namespace: civicpulse
type: Opaque
stringData:
  POSTGRES_DB: civicpulse
  POSTGRES_USER: civicuser
  POSTGRES_PASSWORD: civicpass
  GROQ_API_KEY: PLACEHOLDER