apiVersion: v1
kind: Secret
metadata:
  name: civicpulse-secrets
  namespace: civicpulse
type: Opaque
stringData:
  POSTGRES_DB: civicpulse
  POSTGRES_USER: civicuser
  POSTGRES_PASSWORD: CHANGE_ME
  DATABASE_URL: postgresql+asyncpg://civicuser:CHANGE_ME@postgres:5432/civicpulse
  GROQ_API_KEY: CHANGE_ME
